# Generated by Django 5.1.4 on 2025-01-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspapers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspaper',
            name='topic',
        ),
        migrations.AddField(
            model_name='newspaper',
            name='topic',
            field=models.ManyToManyField(related_name='newspapers', to='newspapers.topic'),
        ),
    ]
